services:

  database:
    image: mariadb:11
    container_name: database
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=password
    volumes:
      - .\mariadb\init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    ports:
      - 3306:3306

  serivce_users:
    build:
      dockerfile: ./users/Dockerfile
    container_name: service_users
    restart: always
    environment:
      - DB_ADDR="root:password@tcp(database:3306)/delivery"
      - HOST=":8000"
    networks:
      - backend
    ports:
      - 8080:8000

  service_items:
    build:
      dockerfile: ./items/Dockerfile
    container_name: service_items
    restart: always
    environment:
      - DB_ADDR="root:password@tcp(database:3306)/delivery"
      - HOST=":8000"
    networks:
      - backend
    ports:
      - 8082:8000

  service_deliveries:
    build:
      dockerfile: ./deliveries/Dockerfile
    container_name: service_deliveries
    environment:
      - DB_ADDR="root:password@tcp(database:3306)/delivery"
      - HOST=":8000"
    restart: always
    networks:
      - backend
    ports:
      - 8083:8000

networks:
  backend:
    driver: bridge
